// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260210105846_AddedQuests")]
    partial class AddedQuests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Socializing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "News"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Driving"
                        });
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesiredConnection")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Age = 21,
                            Bio = "New in the city and looking for new connections!",
                            City = "Sofia",
                            ConcurrencyStamp = "57edb2a2-40ba-4333-87ec-a8aa257114a1",
                            DesiredConnection = 0,
                            DisplayName = "Alex",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "464e6165-20cb-4f6a-87a0-92a5145604dd",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Age = 30,
                            Bio = "Looking for my person",
                            City = "Berlin",
                            ConcurrencyStamp = "36baf2c6-a5d1-4afc-9aba-e70a264bf108",
                            DesiredConnection = 1,
                            DisplayName = "Lidya",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6fd1dc24-6500-43ec-b170-a29398f8d3d5",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "Im heavy into gaming, i'd like to find people to play CS with!!!",
                            City = "Madrid",
                            ConcurrencyStamp = "77cd4472-df81-4bb8-9c18-4c03ccc75287",
                            DesiredConnection = 2,
                            DisplayName = "Liam",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c45d763f-405d-4518-889a-53ade5736aef",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            Age = 31,
                            Bio = "Work in the tech field.Into long night walks.",
                            City = "London",
                            ConcurrencyStamp = "9007f133-32c0-4164-932c-714b92d7f522",
                            DesiredConnection = 1,
                            DisplayName = "Dean",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "740c6e33-910a-4266-804a-dc87a77d518b",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            Age = 27,
                            Bio = "Let's hang out?",
                            City = "Sofia",
                            ConcurrencyStamp = "c4051f7e-5c90-42cf-9dc8-9948d0881d0b",
                            DesiredConnection = 0,
                            DisplayName = "Peter",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e49815c-7cc8-4d85-9f5f-06523ece4aca",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            Age = 44,
                            City = "Rome",
                            ConcurrencyStamp = "25e87d35-962b-4bd1-afaf-fc732a9f0180",
                            DesiredConnection = 1,
                            DisplayName = "Emma",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0f021080-4e30-4e17-ba6d-40ca2ee79502",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            Age = 20,
                            Bio = "Heavy metal!!",
                            City = "Sofia",
                            ConcurrencyStamp = "b71069c9-e4bb-4050-a8d4-feca571fec9a",
                            DesiredConnection = 2,
                            DisplayName = "Luca",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5248105-54eb-4221-a84c-67bab355d631",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            Age = 26,
                            Bio = "Recommend me new music",
                            City = "Madrid",
                            ConcurrencyStamp = "cc98755e-ed15-4884-aab5-caa12a563543",
                            DesiredConnection = 0,
                            DisplayName = "Alexandra",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c25ebdef-8ddc-4283-8c5a-c71e1499f443",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            Age = 33,
                            Bio = "Lets travel the world together!",
                            City = "London",
                            ConcurrencyStamp = "efae049c-b640-42f1-a1c3-d539dc46b4b1",
                            DesiredConnection = 1,
                            DisplayName = "Olivia",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9abfb043-fa21-45e7-b0ca-ebfa03c23229",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "I would like to find a local band. Can play bass pretty good!",
                            City = "London",
                            ConcurrencyStamp = "fa10b5d2-ac01-4861-a81c-b3e087656308",
                            DesiredConnection = 2,
                            DisplayName = "Dan",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "323f1868-bc6f-4680-bc50-571bf490fe9c",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("ProfileInterests");

                    b.HasData(
                        new
                        {
                            ProfileId = "1",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 5
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 11
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 3
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 4
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 9
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 7
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 17
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 23
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 22
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 21
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 14
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 13
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 26
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 24
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 22
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 19
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 17
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 19
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 29
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 27
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 30
                        });
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestInitiatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("QuestInitiatorId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Nexus.Models.QuestJoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestJoiners");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.HasOne("Nexus.Models.Interest", "Interest")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", "Profile")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.HasOne("Nexus.Models.Profile", "QuestInitiator")
                        .WithMany()
                        .HasForeignKey("QuestInitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestInitiator");
                });

            modelBuilder.Entity("Nexus.Models.QuestJoiner", b =>
                {
                    b.HasOne("Nexus.Models.Profile", "Profile")
                        .WithMany("JoinedQuests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Quest", "Quest")
                        .WithMany("QuestJoiners")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Navigation("JoinedQuests");

                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.Navigation("QuestJoiners");
                });
#pragma warning restore 612, 618
        }
    }
}
