// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    partial class NexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RecieverId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Socializing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "News"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Driving"
                        });
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesiredConnection")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Age = 21,
                            Bio = "New in the city and looking for new connections!",
                            City = "Sofia",
                            ConcurrencyStamp = "9eee8c16-aa15-4b34-a8db-91c766573c6a",
                            DesiredConnection = 0,
                            DisplayName = "Alex",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "699b3658-7d88-442f-acb8-0f868de5adda",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Age = 30,
                            Bio = "Looking for my person",
                            City = "Berlin",
                            ConcurrencyStamp = "fcd4cd59-5e62-4cf1-a297-82e698acdcd2",
                            DesiredConnection = 1,
                            DisplayName = "Lidya",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cea40cf9-84ce-4353-b23d-ebbd825afbb4",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "Im heavy into gaming, i'd like to find people to play CS with!!!",
                            City = "Madrid",
                            ConcurrencyStamp = "db9bfa19-73f1-4104-8abb-37f898e60970",
                            DesiredConnection = 2,
                            DisplayName = "Liam",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4524962-99d9-4c49-92d6-0d76fa94d2bd",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            Age = 31,
                            Bio = "Work in the tech field.Into long night walks.",
                            City = "London",
                            ConcurrencyStamp = "196d5ade-dcfc-4349-b7ed-b6888b769b41",
                            DesiredConnection = 1,
                            DisplayName = "Dean",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b992bbea-45d1-47a5-963f-5e06655bb4d5",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            Age = 27,
                            Bio = "Let's hang out?",
                            City = "Sofia",
                            ConcurrencyStamp = "07c5bc61-2f8a-4bb3-acb2-89d770f49584",
                            DesiredConnection = 0,
                            DisplayName = "Peter",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52cc8469-9376-4e8b-9c64-07fa35bcffe0",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            Age = 44,
                            City = "Rome",
                            ConcurrencyStamp = "b80d85e3-d67f-4538-930a-b43e9937b11e",
                            DesiredConnection = 1,
                            DisplayName = "Emma",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f35279b8-552e-4d19-80ed-9a1e3d770b39",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            Age = 20,
                            Bio = "Heavy metal!!",
                            City = "Sofia",
                            ConcurrencyStamp = "f454af75-fc20-47b6-ad6c-cbe09ae2c0af",
                            DesiredConnection = 2,
                            DisplayName = "Luca",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "baffbe33-2d67-4d76-ad55-3e1f7b3b12e7",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            Age = 26,
                            Bio = "Recommend me new music",
                            City = "Madrid",
                            ConcurrencyStamp = "d9286632-1fa3-4890-ab29-3d4f61e625ed",
                            DesiredConnection = 0,
                            DisplayName = "Alexandra",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6aa41cd4-68b2-4480-aa57-2d3d3d3822a6",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            Age = 33,
                            Bio = "Lets travel the world together!",
                            City = "London",
                            ConcurrencyStamp = "2c00d0b3-b37c-40ef-944d-a5628885a4c3",
                            DesiredConnection = 1,
                            DisplayName = "Olivia",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "05347c4c-39b4-4146-9917-604cb736949c",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "I would like to find a local band. Can play bass pretty good!",
                            City = "London",
                            ConcurrencyStamp = "cba69389-83db-45d3-8bcb-4e1a730927fe",
                            DesiredConnection = 2,
                            DisplayName = "Dan",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5e8227c-84cf-4463-802f-f622b94f72ba",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("NVARCHAR(450)");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("ProfileInterests");

                    b.HasData(
                        new
                        {
                            ProfileId = "1",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 5
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 11
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 3
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 4
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 9
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 7
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 17
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 23
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 22
                        },
                        new
                        {
                            ProfileId = "5",
                            InterestId = 21
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 14
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 13
                        },
                        new
                        {
                            ProfileId = "6",
                            InterestId = 26
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 24
                        },
                        new
                        {
                            ProfileId = "7",
                            InterestId = 22
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 19
                        },
                        new
                        {
                            ProfileId = "8",
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 17
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = "9",
                            InterestId = 19
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 29
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 27
                        },
                        new
                        {
                            ProfileId = "10",
                            InterestId = 30
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Models.FriendRequest", b =>
                {
                    b.HasOne("Nexus.Models.Profile", "Reciever")
                        .WithMany()
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.HasOne("Nexus.Models.Interest", "Interest")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", "Profile")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Navigation("ProfileInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
