// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203163642_InitialIdentityConfiguration")]
    partial class InitialIdentityConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Models.FriendRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecieverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Socializing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "News"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Driving"
                        });
                });

            modelBuilder.Entity("Nexus.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<int>("DesiredConnection")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Bio = "New in the city and looking for new connections!",
                            City = "Sofia",
                            DesiredConnection = 0,
                            Name = "Alex"
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            Bio = "Looking for my person",
                            City = "Berlin",
                            DesiredConnection = 1,
                            Name = "Lidya"
                        },
                        new
                        {
                            Id = 3,
                            Age = 19,
                            Bio = "Im heavy into gaming, i'd like to find people to play CS with!!!",
                            City = "Madrid",
                            DesiredConnection = 2,
                            Name = "Liam"
                        },
                        new
                        {
                            Id = 4,
                            Age = 31,
                            Bio = "Work in the tech field.Into long night walks.",
                            City = "London",
                            DesiredConnection = 1,
                            Name = "Dean"
                        },
                        new
                        {
                            Id = 5,
                            Age = 27,
                            Bio = "Let's hang out?",
                            City = "Sofia",
                            DesiredConnection = 0,
                            Name = "Peter"
                        },
                        new
                        {
                            Id = 6,
                            Age = 44,
                            City = "Rome",
                            DesiredConnection = 1,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = 7,
                            Age = 20,
                            Bio = "Heavy metal!!",
                            City = "Sofia",
                            DesiredConnection = 2,
                            Name = "Luca"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            Bio = "Recommend me new music",
                            City = "Madrid",
                            DesiredConnection = 0,
                            Name = "Alexandra"
                        },
                        new
                        {
                            Id = 9,
                            Age = 33,
                            Bio = "Lets travel the world together!",
                            City = "London",
                            DesiredConnection = 1,
                            Name = "Olivia"
                        },
                        new
                        {
                            Id = 10,
                            Age = 19,
                            Bio = "I would like to find a local band. Can play bass pretty good!",
                            City = "London",
                            DesiredConnection = 2,
                            Name = "Dan"
                        });
                });

            modelBuilder.Entity("Nexus.Models.UserInterest", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("UsersInterests");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            InterestId = 2
                        },
                        new
                        {
                            UserId = 1,
                            InterestId = 5
                        },
                        new
                        {
                            UserId = 1,
                            InterestId = 6
                        },
                        new
                        {
                            UserId = 2,
                            InterestId = 6
                        },
                        new
                        {
                            UserId = 2,
                            InterestId = 11
                        },
                        new
                        {
                            UserId = 2,
                            InterestId = 3
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 4
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 16
                        },
                        new
                        {
                            UserId = 3,
                            InterestId = 9
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 7
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 15
                        },
                        new
                        {
                            UserId = 4,
                            InterestId = 17
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 23
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 22
                        },
                        new
                        {
                            UserId = 5,
                            InterestId = 21
                        },
                        new
                        {
                            UserId = 6,
                            InterestId = 14
                        },
                        new
                        {
                            UserId = 6,
                            InterestId = 13
                        },
                        new
                        {
                            UserId = 6,
                            InterestId = 26
                        },
                        new
                        {
                            UserId = 7,
                            InterestId = 2
                        },
                        new
                        {
                            UserId = 7,
                            InterestId = 24
                        },
                        new
                        {
                            UserId = 7,
                            InterestId = 22
                        },
                        new
                        {
                            UserId = 8,
                            InterestId = 2
                        },
                        new
                        {
                            UserId = 8,
                            InterestId = 19
                        },
                        new
                        {
                            UserId = 8,
                            InterestId = 15
                        },
                        new
                        {
                            UserId = 9,
                            InterestId = 17
                        },
                        new
                        {
                            UserId = 9,
                            InterestId = 16
                        },
                        new
                        {
                            UserId = 9,
                            InterestId = 19
                        },
                        new
                        {
                            UserId = 10,
                            InterestId = 29
                        },
                        new
                        {
                            UserId = 10,
                            InterestId = 27
                        },
                        new
                        {
                            UserId = 10,
                            InterestId = 30
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Models.FriendRequest", b =>
                {
                    b.HasOne("Nexus.Models.User", "UserReciever")
                        .WithMany()
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Models.User", "UserSender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserReciever");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("Nexus.Models.UserInterest", b =>
                {
                    b.HasOne("Nexus.Models.Interest", "Interest")
                        .WithMany("UserInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexus.Models.User", "User")
                        .WithMany("UserInterest")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Navigation("UserInterest");
                });

            modelBuilder.Entity("Nexus.Models.User", b =>
                {
                    b.Navigation("UserInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
