// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Data.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260214200221_SeedsFixed")]
    partial class SeedsFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Socializing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "News"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Driving"
                        });
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesiredConnection")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Age = 21,
                            Bio = "New in the city and looking for new connections!",
                            City = "Sofia",
                            ConcurrencyStamp = "b46058b7-875d-47ac-ad71-cd2955575f33",
                            DesiredConnection = 0,
                            DisplayName = "Alex",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "64b9e6eb-1a8c-40ba-b2ed-e5cf650f0012",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Age = 30,
                            Bio = "Looking for my person",
                            City = "Berlin",
                            ConcurrencyStamp = "0ed8a136-8961-45e6-ba6b-d11852d8e19d",
                            DesiredConnection = 1,
                            DisplayName = "Lidya",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02795cf0-bbe8-4a83-b44a-451b347daa8f",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "Im heavy into gaming, i'd like to find people to play CS with!!!",
                            City = "Madrid",
                            ConcurrencyStamp = "8612d5be-07e7-4353-b5ad-4605facff1be",
                            DesiredConnection = 2,
                            DisplayName = "Liam",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8fc3b581-2a7d-4316-9367-a6ad209a18e3",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            Age = 31,
                            Bio = "Work in the tech field.Into long night walks.",
                            City = "London",
                            ConcurrencyStamp = "a60762f3-fa85-49cd-8147-98b3e30fd234",
                            DesiredConnection = 1,
                            DisplayName = "Dean",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c4ea5fd2-59a2-4955-a47d-04beddbf0a27",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("ProfileInterests");

                    b.HasData(
                        new
                        {
                            ProfileId = "1",
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 5
                        },
                        new
                        {
                            ProfileId = "1",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 11
                        },
                        new
                        {
                            ProfileId = "2",
                            InterestId = 3
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 4
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = "3",
                            InterestId = 9
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 7
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = "4",
                            InterestId = 17
                        });
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestInitiatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("QuestInitiatorId");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Join us for some fishing, cooking and camping near the river!",
                            QuestInitiatorId = "4",
                            Title = "Camping near the river"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Im looking for people to play cs with so i'd love for us to form a squad!",
                            QuestInitiatorId = "3",
                            Title = "Gaming night"
                        });
                });

            modelBuilder.Entity("Nexus.Models.QuestJoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestJoiners");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Nexus.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Models.ProfileInterests", b =>
                {
                    b.HasOne("Nexus.Models.Interest", "Interest")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Profile", "Profile")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.HasOne("Nexus.Models.Profile", "QuestInitiator")
                        .WithMany()
                        .HasForeignKey("QuestInitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestInitiator");
                });

            modelBuilder.Entity("Nexus.Models.QuestJoiner", b =>
                {
                    b.HasOne("Nexus.Models.Profile", "Profile")
                        .WithMany("JoinedQuests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.Models.Quest", "Quest")
                        .WithMany("QuestJoiners")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Nexus.Models.Interest", b =>
                {
                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Models.Profile", b =>
                {
                    b.Navigation("JoinedQuests");

                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Models.Quest", b =>
                {
                    b.Navigation("QuestJoiners");
                });
#pragma warning restore 612, 618
        }
    }
}
