// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Data;

#nullable disable

namespace Nexus.Data.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260327165037_QuestInterestAdded")]
    partial class QuestInterestAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexus.Data.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cooking"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Travelling"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Photography"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Animals"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Board Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Meditation"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Writing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Languages"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nature"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Socializing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volunteering"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 23,
                            Name = "News"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Crafts"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Drawing"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Driving"
                        });
                });

            modelBuilder.Entity("Nexus.Data.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DesiredConnection")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AccessFailedCount = 0,
                            Age = 21,
                            Bio = "New in the city and looking for new connections!",
                            City = "Sofia",
                            ConcurrencyStamp = "97ad1874-62f6-4526-85b0-e7b89497c2bc",
                            DesiredConnection = 0,
                            DisplayName = "Alex",
                            EmailConfirmed = false,
                            ExperiencePoints = 800,
                            Level = 9,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AccessFailedCount = 0,
                            Age = 30,
                            Bio = "Looking for my person",
                            City = "Berlin",
                            ConcurrencyStamp = "e1b50b85-eb63-4453-8c1b-9cc3d140fc9b",
                            DesiredConnection = 1,
                            DisplayName = "Lidya",
                            EmailConfirmed = false,
                            ExperiencePoints = 350,
                            Level = 4,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AccessFailedCount = 0,
                            Age = 19,
                            Bio = "Im heavy into gaming, i'd like to find people to play CS with!!!",
                            City = "Madrid",
                            ConcurrencyStamp = "28820cce-4121-4f09-bf53-57949c79009f",
                            DesiredConnection = 2,
                            DisplayName = "Liam",
                            EmailConfirmed = false,
                            ExperiencePoints = 1200,
                            Level = 13,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            AccessFailedCount = 0,
                            Age = 31,
                            Bio = "Work in the tech field.Into long night walks.",
                            City = "London",
                            ConcurrencyStamp = "b1fe8267-ba1d-4489-9941-63b9f5d6b1fb",
                            DesiredConnection = 1,
                            DisplayName = "Dean",
                            EmailConfirmed = false,
                            ExperiencePoints = 650,
                            Level = 7,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            AccessFailedCount = 0,
                            Age = 24,
                            Bio = "Love art galleries and coffee spots. Always up for creative activities!",
                            City = "Paris",
                            ConcurrencyStamp = "a9d8c755-1eae-4aeb-98c7-d73b473ef323",
                            DesiredConnection = 0,
                            DisplayName = "Maya",
                            EmailConfirmed = false,
                            ExperiencePoints = 520,
                            Level = 6,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            AccessFailedCount = 0,
                            Age = 27,
                            Bio = "Cycling enthusiast and fitness lover. Looking for active people.",
                            City = "Amsterdam",
                            ConcurrencyStamp = "1c1e31b6-002e-42e3-9b25-aa3c064a464c",
                            DesiredConnection = 2,
                            DisplayName = "Noah",
                            EmailConfirmed = false,
                            ExperiencePoints = 950,
                            Level = 10,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            AccessFailedCount = 0,
                            Age = 28,
                            Bio = "Foodie and traveler. Let’s explore new places together!",
                            City = "Amsterdam",
                            ConcurrencyStamp = "3ff66ed6-147b-4396-a48d-a4411b65d5f4",
                            DesiredConnection = 0,
                            DisplayName = "Elena",
                            EmailConfirmed = false,
                            ExperiencePoints = 430,
                            Level = 5,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            AccessFailedCount = 0,
                            Age = 29,
                            Bio = "Into tech, startups and hackathons. Building cool stuff.",
                            City = "Sofia",
                            ConcurrencyStamp = "54d1efd7-f257-43a0-94a3-225d6a42787a",
                            DesiredConnection = 2,
                            DisplayName = "Victor",
                            EmailConfirmed = false,
                            ExperiencePoints = 1100,
                            Level = 12,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Nexus.Data.Models.ProfileInterest", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("ProfileInterests");

                    b.HasData(
                        new
                        {
                            ProfileId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            InterestId = 2
                        },
                        new
                        {
                            ProfileId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            InterestId = 5
                        },
                        new
                        {
                            ProfileId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            InterestId = 6
                        },
                        new
                        {
                            ProfileId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            InterestId = 11
                        },
                        new
                        {
                            ProfileId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            InterestId = 3
                        },
                        new
                        {
                            ProfileId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            InterestId = 4
                        },
                        new
                        {
                            ProfileId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            InterestId = 9
                        },
                        new
                        {
                            ProfileId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            InterestId = 7
                        },
                        new
                        {
                            ProfileId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            InterestId = 17
                        },
                        new
                        {
                            ProfileId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            InterestId = 8
                        },
                        new
                        {
                            ProfileId = new Guid("a5555555-5555-5555-5555-555555555555"),
                            InterestId = 26
                        },
                        new
                        {
                            ProfileId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            InterestId = 5
                        },
                        new
                        {
                            ProfileId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            InterestId = 15
                        },
                        new
                        {
                            ProfileId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            InterestId = 16
                        },
                        new
                        {
                            ProfileId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            InterestId = 7
                        },
                        new
                        {
                            ProfileId = new Guid("a7777777-7777-7777-7777-777777777777"),
                            InterestId = 20
                        },
                        new
                        {
                            ProfileId = new Guid("a8888888-8888-8888-8888-888888888888"),
                            InterestId = 22
                        });
                });

            modelBuilder.Entity("Nexus.Data.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestInitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RewardXp")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("QuestInitiatorId");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Join us for some fishing, cooking and camping near the river!",
                            Difficulty = 2,
                            QuestInitiatorId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            RewardXp = 200,
                            Status = 1,
                            Title = "Camping near the river"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Im looking for people to play cs with so i'd love for us to form a squad!",
                            Difficulty = 0,
                            QuestInitiatorId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            RewardXp = 50,
                            Status = 0,
                            Title = "Gaming night"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Let's clean the city!",
                            Difficulty = 1,
                            QuestInitiatorId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            RewardXp = 125,
                            Status = 0,
                            Title = "Community Work"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Looking for committed people to stay consistent and push limits for 30 days.",
                            Difficulty = 2,
                            QuestInitiatorId = new Guid("a6666666-6666-6666-6666-666666666666"),
                            RewardXp = 200,
                            Status = 0,
                            Title = "30-Day Fitness Challenge"
                        });
                });

            modelBuilder.Entity("Nexus.Data.Models.QuestInterest", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.HasKey("QuestId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("QuestInterests");

                    b.HasData(
                        new
                        {
                            QuestId = 1,
                            InterestId = 6
                        },
                        new
                        {
                            QuestId = 1,
                            InterestId = 15
                        },
                        new
                        {
                            QuestId = 2,
                            InterestId = 4
                        },
                        new
                        {
                            QuestId = 3,
                            InterestId = 21
                        },
                        new
                        {
                            QuestId = 4,
                            InterestId = 5
                        },
                        new
                        {
                            QuestId = 4,
                            InterestId = 16
                        });
                });

            modelBuilder.Entity("Nexus.Data.Models.QuestJoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestJoiners");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nexus.Data.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nexus.Data.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Data.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nexus.Data.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexus.Data.Models.ProfileInterest", b =>
                {
                    b.HasOne("Nexus.Data.Models.Interest", "Interest")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Data.Models.Profile", "Profile")
                        .WithMany("ProfileInterest")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Nexus.Data.Models.Quest", b =>
                {
                    b.HasOne("Nexus.Data.Models.Profile", "QuestInitiator")
                        .WithMany()
                        .HasForeignKey("QuestInitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestInitiator");
                });

            modelBuilder.Entity("Nexus.Data.Models.QuestInterest", b =>
                {
                    b.HasOne("Nexus.Data.Models.Interest", "Interest")
                        .WithMany("QuestInterest")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.Data.Models.Quest", "Quest")
                        .WithMany("QuestInterest")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Nexus.Data.Models.QuestJoiner", b =>
                {
                    b.HasOne("Nexus.Data.Models.Profile", "Profile")
                        .WithMany("JoinedQuests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nexus.Data.Models.Quest", "Quest")
                        .WithMany("QuestJoiners")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Nexus.Data.Models.Interest", b =>
                {
                    b.Navigation("ProfileInterest");

                    b.Navigation("QuestInterest");
                });

            modelBuilder.Entity("Nexus.Data.Models.Profile", b =>
                {
                    b.Navigation("JoinedQuests");

                    b.Navigation("ProfileInterest");
                });

            modelBuilder.Entity("Nexus.Data.Models.Quest", b =>
                {
                    b.Navigation("QuestInterest");

                    b.Navigation("QuestJoiners");
                });
#pragma warning restore 612, 618
        }
    }
}
