<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Data\Nexus.Data.csproj" />
    <ProjectReference Include="..\Nexus.GCommon\Nexus.GCommon.csproj" />
    <ProjectReference Include="..\WebNexus.ViewModels\Nexus.ViewModels.csproj" />
  </ItemGroup>

</Project>
